### PR TITLE
feat: upgrade Nx to `16.*`

### PR DESCRIPTION
**Pull request by arturovt**

### CODE REVIEW

**Comment by arturovt** [comment]
@twittwer friendly ping.

**Comment by twittwer** [comment]
Oh, sorry - Will have a look and prepare an update during the weekend

**Review by twittwer — APPROVED** [review]

**Comment by twittwer** [comment]
@arturovt Thx for your work and sorry for the delay.
I just added an update to the currently latest version (16.4.0)

**Comment by twittwer** [comment]
Released with version 1.10.0 🎉

**Pull request merged**
