### PR TITLE
Feature/full workspace html generator

### PR DESCRIPTION
**Pull request by mattgek**
This is a proposal. Not sure if @twittwer is open for suggestions. What do you think about it? Also I would need some help with testing and spawn errors for the schematic tests. 

I made it a draft for that reason. 🤞 🙇

### CODE REVIEW

**Comment by twittwer** [comment]
Thx for your contribution 👍  
I will have a look at it, but it may take until Sunday.

**Comment by mattgek** [comment]
Ok thanks

**Comment by twittwer** [comment]
Sorry for the delayed reaction - I'm a bit busy as I just moved, but I will try to have a more detailed look.

👍 The idea looks interesting
🤔 I'm just a bit concerned about the assets I would like to not include them in the Repo and load them from external sources.
💭 Another idea would be to load project's compodoc in an iframe while a minimalistic sidebar (with the other projects) stays visible for an easy cross-project navigation.

**Comment by mattgek** [comment]
> Sorry for the delayed reaction - I'm a bit busy as I just moved, but I will try to have a more detailed look.
> 
> 👍 The idea looks interesting
> 🤔 I'm just a bit concerned about the assets I would like to not include them in the Repo and load them from external sources.
> 💭 Another idea would be to load project's compodoc in an iframe while a minimalistic sidebar (with the other projects) stays visible for an easy cross-project navigation.

-I  also had the a concern about the assets. I'll look into that.
- Regarding the iFrames idea, is this from the assumption that every app/lib compodoc is hosted?

**Pull request closed without merging**
